datasets:
  raw:
    housing:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/House_price/housing.csv
      driver_params: {}
  
  cleaned:
    housing:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/House_price/housing.parquet
      driver_params: {}
      
  train:
    housing:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/House_price/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/House_price/target.parquet
        driver_params:
          save:
            index: False
  test:
    housing:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/House_price/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/House_price/target.parquet
        driver_params:
          save:
            index: False
  
  

  
  
  
  